start using pnpm
ember-cli/ember-cli-deprecation-workflow pull request #188
Opened 2024-06-24 15:11 UTC by mansona

2024-06-24 17:30 UTC, NullVoxPopuli commented on .github/workflows/ci.yml
> +          version: 8
Use v9 pls <3

2024-06-24 17:30 UTC, NullVoxPopuli requested changes
Should use pnpm 9

2024-06-25 15:04 UTC, mansona commented
we discussed this in the Tooling team and it turns out that the PR was wrong, but not because of the pnpm version. I dropped the node version that CI was using to the same that was in volta before this PR 👍

2024-06-25 15:35 UTC, NullVoxPopuli approved these changes

2024-06-25 15:45 UTC, merged